### ISSUE TITLE
"<" and ">" are not escaped in strings used as input for XML

### ISSUE THREAD

**Issue by solomchuk** [ESRIN-RSS/Excel-to-ISO-converter#22]
The "<" and ">" characters are not escaped properly in string values extracted from the Excel files. Example string part in Excel:
"Ground Sampling Distance (nadir): Panchromatic 0.86m and Multispectral 1.0m for SkySat-1&2, Panchromatic 0.72m and Multispectral 1.0m for SkySat-3 to 13
Accuracy: <50m RMSE"

This causes errors like the following:

> 2020-02-26 13:16:15,911 [INFO ]  Sheet1 is a valid template
2020-02-26 13:16:15,912 [ERROR]  Sheet2 is not a valid template. Skipping
2020-02-26 13:16:15,912 [INFO ]  Parsing file C:\Users\solomcukm\Desktop\EOCAT\CP-509\collection-metadata-xlsx\SkySat Full Archive and tasking.xlsx
2020-02-26 13:16:15,912 [INFO ]  Checking mandatory fields...
Traceback (most recent call last):
  File "C:\Users\solomcukm\Desktop\EOCAT\CP-509\Excel-to-ISO-converter\rss-xls-to-xml-translator.py", line 660, in <module>
    xml = xml.dom.minidom.parseString(nfiledata.replace("\n",""))
  File "C:\Users\solomcukm\AppData\Local\Continuum\anaconda3\envs\excel-to-iso\lib\xml\dom\minidom.py", line 1968, in parseString
    return expatbuilder.parseString(string)
  File "C:\Users\solomcukm\AppData\Local\Continuum\anaconda3\envs\excel-to-iso\lib\xml\dom\expatbuilder.py", line 925, in parseString
    return builder.parseString(string)
  File "C:\Users\solomcukm\AppData\Local\Continuum\anaconda3\envs\excel-to-iso\lib\xml\dom\expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 1, column 5806

As a result of the error, the XML file is not written out.

Possible solution - use xml.sax.saxutils.escape to replace "<", "&" and ">" with "&lt;", "&amp;",  and "&gt;", respectively.

**Comment by solomchuk** [comment]
In my local copy of the script, I fixed this with the following:

```
from xml.sax.saxutils import escape

def clean_field_val(val, fieldcode=""):
    # print(val,fieldcode)
    if isinstance(val, datetime.datetime):
        val = datetime.datetime.strptime(str(val),'%Y-%m-%d %H:%M:%S')
        val = val.strftime('%Y-%m-%d')
    # elif str(val).find("&")>0:
    #     val = quote(val, safe='')
    elif (fieldcode == "OI_PH" or fieldcode == "OI_F") and not val.find("+") >= 0:
        val = "+"+str(val)
    elif str(val).find("µ") > 0:
        val = val.encode('utf-8').decode('cp1252')
    else:
        val = str(val)
    return escape(val.strip())
```

Need to run some tests to ensure this change does not introduce any regressions.

**Comment by vascobnunes** [comment]
OK, thank you! let me know the outcome of your tests, please, so that I can commit the changes.

**Comment by solomchuk** [comment]
So far I could not find any issues stemming from this change. I'd say you can commit.

**Comment by vascobnunes** [comment]
ok, thank you

**Comment by vascobnunes** [comment]
@solomchuk

![image](https://user-images.githubusercontent.com/586591/76007814-90ae3580-5f06-11ea-8871-19514c652ab7.png)

**Comment by solomchuk** [comment]
Been a while since the last comment, so just to reach an agreement - yes, I confirm the above.
